spring.application.name=buildsense-ai

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.chat.options.temperature=0.2

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2