spring.application.name=buildsense-ai

spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.chat.options.temperature=0.2

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2